#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "exampleSeesaw/geo.inc.c"
#include "raisePlatform/geo.inc.c"
#include "doubleCherry/geo.inc.c"
#include "mini_mario/geo.inc.c"
#include "end_gate/geo.inc.c"
#include "exclamation_point/geo.inc.c"
#include "exclamation_point_2/geo.inc.c"
#include "mini_mario_button/geo.inc.c"
#include "turn_plane/geo.inc.c"
#include "direction_plate/geo.inc.c"
#include "jump_plane/geo.inc.c"