extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_1[26];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_Grass_Example[];
extern Gfx mat_revert_bob_dl_Grass_Example[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1[];
