extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_0[308];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_1[14];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_2[160];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_2[];
extern Gfx mat_pss_dl_Grass_Example[];
extern Gfx mat_revert_pss_dl_Grass_Example[];
extern Gfx mat_pss_dl_f3dlite_material_004[];
extern Gfx mat_revert_pss_dl_f3dlite_material_004[];
extern Gfx mat_pss_dl_f3dlite_material[];
extern Gfx mat_revert_pss_dl_f3dlite_material[];
extern Gfx pss_dl_Cube_mesh_layer_1[];
