extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern u8 lll_dl_lll_textures_09000_rgba16_ci8[];
extern u8 lll_dl_lll_textures_09000_rgba16_pal_rgba16[];
extern u8 lll_dl_lll_textures_04800_rgba16_rgba16[];
extern u8 lll_dl_lll_textures_07800_rgba16_ci8[];
extern u8 lll_dl_lll_textures_07800_rgba16_pal_rgba16[];
extern u8 lll_dl_lll_textures_03800_rgba16_rgba16[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx lll_dl_Level_Mesh_mesh_layer_5_vtx_0[8];
extern Gfx lll_dl_Level_Mesh_mesh_layer_5_tri_0[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_0[4];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_1[20];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx lll_dl_Level_Mesh_mesh_layer_1_vtx_2[4];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Gfx mat_lll_dl_Lava[];
extern Gfx mat_revert_lll_dl_Lava[];
extern Gfx mat_lll_dl_f3dlite_material_001[];
extern Gfx mat_revert_lll_dl_f3dlite_material_001[];
extern Gfx mat_lll_dl_f3dlite_material_002[];
extern Gfx mat_revert_lll_dl_f3dlite_material_002[];
extern Gfx mat_lll_dl_f3dlite_material_003[];
extern Gfx mat_revert_lll_dl_f3dlite_material_003[];
extern Gfx lll_dl_Level_Mesh_mesh_layer_5[];
extern Gfx lll_dl_Level_Mesh_mesh_layer_1[];
